### ISSUE TITLE
AppUtils + ofxGui 

### ISSUE THREAD

**Issue by barrylachapelle** [danomatika/ofxAppUtils#7] opened 2016-01-26 08:46 UTC
Hey Dan,

I am having issues creating a new project through Project Generator with both AppUtils and oFxGui. I can create with either but not both. Anyone else having issues with this?

Thanks Dan.

![screen shot 2016-01-26 at 5 40 35 pm](https://cloud.githubusercontent.com/assets/1087169/12576106/ba067b00-c454-11e5-8790-d8cdccb37c0b.png)
![screen shot 2016-01-26 at 5 40 50 pm](https://cloud.githubusercontent.com/assets/1087169/12576107/ba0becca-c454-11e5-8924-fcfa74300c19.png)

**Comment by danomatika** [comment] 2016-01-26 09:06
Just tried the same and still working for me. Any thoughts @arturoc and/or @backercp? Seems to fail on the "android:" target for him?

<img width="612" alt="screen shot 2016-01-26 at 2 03 16 am" src="https://cloud.githubusercontent.com/assets/480637/12576468/1b51d2c6-c3d1-11e5-974a-3e4c73128880.png">

<img width="612" alt="screen shot 2016-01-26 at 2 03 21 am" src="https://cloud.githubusercontent.com/assets/480637/12576469/1fc0709c-c3d1-11e5-9f7e-2deb401c9937.png">

**Comment by arturoc** [comment] 2016-01-26 10:48
@barrylachapelle can you post the full output in the console?

**Comment by barrylachapelle** [comment] 2016-01-26 11:18
@arturoc sure thing
--------------

Command failed: /bin/sh -c "/Users/barrylachapelle/Dropbox (IDEO)/05. Playground/oF/0.9.0/ios/projectGenerator-ios/projectGenerator.app/Contents/Resources/app/app/projectGenerator" -v -o"/Users/barrylachapelle/Dropbox (IDEO)/05. Playground/oF/0.9.0/ios" -a"ofxAppUtils,ofxGui" -p"ios" "/Users/barrylachapelle/Dropbox (IDEO)/05. Playground/oF/0.9.0/ios/apps/myApps/AUTest"
[ error ] Error parsing ofxAppUtils addon_config.mk
		line 33: android:
		sectionName unknown not recognized

**Comment by danomatika** [comment] 2016-04-14 15:45
I haven't been abel to reproduce this so far.

**Comment by danomatika** [comment] 2016-11-03 21:24
Closing due to lack of updates.

**Closed by danomatika** 2016-11-03 21:24 UTC
